dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'

networks:
  polygon-test:
    lot_coin: '0xE1Db74F56b719535abc68E29290eC2E844AC069e'